### ISSUE TITLE
Supporting rGFA

### ISSUE THREAD

**Issue by ggonnella** [ggonnella/gfapy#11]
@egoltsman asked for supporting rGFA-specific tags.

A specification of rGFA is here ( https://github.com/lh3/gfatools/blob/master/doc/rGFA.md )
@egoltsman: should this specification be supported or which other, otherwise?

**Comment by ggonnella** [comment]
If I see correctly rGFA is a subset of GFA1, with the custom tags SN, SO, SR, which must be present on each segment and where all L must have 0 length. But in the example in an issue of the minigraph repository (https://github.com/lh3/minigraph/issues/9), I see additional tags also on the L lines. Where is their definition?

**Comment by egoltsman** [comment]
Good question. These tags are produced by minigraph (which is a work in progress), so I would assume they're custom since the formal spec doesnt define them.  I will post the question on the minigraph board.  
If all the new tags are considered custom (i.e. not predefined) then the only issue in gfapy right now are the validation methods which currently require custom tags to be lower case.    But I think for formal support of rGFA it would be great to have them predefined so that classes and methods could be added for them as the application space gets developed for this format.    Thanks!

**Comment by egoltsman** [comment]
So yes, the tags on the edges were added by Heng Li after after he had posted the rGRA spec and I guess he hasn't updated it.  I hope this helps.

**Comment by ggonnella** [comment]
Great. I'm going to define which operation should be supported on rGFA records, so I can write tests and do test-driven development. You can probably help me with that?

First things I think of now:
- support of the necessary tags without considering them custom tags
- validation on the presence of the tags on each S line and the overlap of L lines
- conversion to GFA1 spec-compliant by changing tags to lower case
- conversion from GFA1 by making tags upper case and validation of L overlap

**Comment by ggonnella** [comment]
I created an own [branch rgfa](/ggonnella/gfapy/tree/rgfa) for this enhancement.

**Comment by ggonnella** [comment]
Experimental support for rGFA is now available.

To use it, dialect="rgfa" must be set in the constructor Gfa() or passed to the Gfa.from_file() method. After this, upper case application specific tags are allowed and validation is performed,
to ensure the correct tags and lines are available. Please see gfapy/rgfa.py for the validation code. Validation can also be run manually using ```validate()``` (runs all validations) on the Gfa object or ```validate_rgfa()``` (calls only the rGFA specific validations). A ```stable_sequence_names``` method is also provided, which returns the list of stable sequences mentioned in SN tags.

**Comment by egoltsman** [comment]
Great! Thank you for the quick response!!

**Comment by egoltsman** [comment]
Ah, didn't notice your earlier comment.  On the last two bullets:

* conversion to GFA1 spec-compliant by changing tags to lower case
-What's the reason/need for conversion to GFA1?  I would think that converting to GFA2 is well worthwhile, and you already provide the methods for that.  But rGFA is essentially GFA1 anyway, so why convert and force the tag change?

*conversion from GFA1 by making tags upper case and validation of L overlap
- As far the overlap, do you mean validation that there is none?  That's the requirement of rGFA, I believe.

**Comment by ggonnella** [comment]
I indeed did not implement the conversion to standard compliant GFA1. This would be done just by converting the case of the tags. This would be a step to convert to GFA2. But I leave it, unless we find a concrete usage case.

Overlap: exactly. I checked that they are all 0M. There is probably more one can check, but it's a bit difficult to say, since rGFA is work in progress. If you have suggestions, please tell me.

If would be nice if you can try working with the branch a bit and give me feedback or further examples. Also if you can have a look to the validations in the code and tell me if you have suggestions for other possible checks or any operations to support.

On April 19, 2020 7:03:49 AM GMT+02:00, Eugene Goltsman <notifications@github.com> wrote:
>Ah, didn't notice your earlier comment.  On the last two bullets:
>
>* conversion to GFA1 spec-compliant by changing tags to lower case
>-What's the reason/need for conversion to GFA1?  I would think that
>converting to GFA2 is well worthwhile, and you already provide the
>methods for that.  But rGFA is essentially GFA1 anyway, so why convert
>and force the tag change?
>
>*conversion from GFA1 by making tags upper case and validation of L
>overlap
>- As far the overlap, do you mean validation that there is none? 
>That's the requirement of rGFA, I believe.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ggonnella/gfapy/issues/11#issuecomment-616033023

-- 
Dr. Giorgio Gonnella

**Comment by egoltsman** [comment]
Thank you for your attention to this.  On my end I've been thinking of ways to query these reference graphs.  Users are often interested in positional context of variants, e.g. "I want to see all variants upstream of gene X on the reference".  There is no unified coordinate system currently impeded in rGFA, but let's assume one has established it externally.   One could then add it as custom tags (or custom positional fields).  That will enable also adding genome features like gene annotations, for instance.  The end goal is to be able to query the graph and extract information (e.g. sub-graphs) by specifying *global* coordinates or features rather than by segment or edge id, which are meaningless outside of the graph.   Just as a Fragment (in GFA2) has positional fields to place it on a segment, a Segment, in turn, could have custom "global" positional fields to place it on a common global coordinate system.  

I can see something similar being described in the Custom_records->Extensions section of the documentation, and I'm going to try and experiment with these.  But if you have any additional thoughts - I'd love to hear it.   One of my worries is how scalable it would be to search every segment's custom tags, or if an index of some sort will be needed.

Regards
Gene

**Comment by egoltsman** [comment]
Hello,
Instead of staring a new issue I'll just add this question here.   It seems like header lines are explicitly not allowed in the rGFA dialect.  When validating after explicitly adding the header line ( gfa.add_line("H\tVN:Z:1.0) )  I get  
```
... , line 52, in _validate_rgfa_no_headers
raise  gfapy.ValueError("rGFA does not support header lines").
```
Note that the input rGFA indeed lacks the header line, but, as one would often use gfapy to output a graph in the standard GFA1 format,  including the header line to the gfa object would be necessary at some point.   Or is there a intermediate type casting step needed to go from the 'rgfa' dialect to plain 'gfa'?

Thanks!

**Comment by egoltsman** [comment]
Ok, I think I found a solution:  explicitly re-assign the dialect back to 'gfa'.  Then all validations pass.

**Comment by ggonnella** [comment]
Exactly. I think it's an acceptable API for this operation.

On June 25, 2020 12:54:59 AM GMT+02:00, Eugene Goltsman <notifications@github.com> wrote:
>Ok, I think I found a solution:  explicitly re-assign the dialect back
>to 'gfa'.  Then all validations pass.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ggonnella/gfapy/issues/11#issuecomment-649115156

-- 
Dr. Giorgio Gonnella
