### ISSUE TITLE
gfapy-convert: has no identifier Path conversion to GFA2 failed

### ISSUE THREAD

**Issue by sjackman** [ggonnella/gfapy#4]
`gfapy-convert` requires custom `id:Z` tags to convert from GFA1 to GFA2, which means it's not possible to convert a typical GFA 1 file with paths that does not have such IDs. GFA 2 does not explicitly required edges IDs when the paths are unambiguous, which is the case for GFA 1.

Alternatively, the edges could be numbered sequentially.

```gfa
S	A	AAAAAAACGT
S	B	ACGTCCACGT
L	A	+	B	+	4M
P	P1	A+,B+	4M
```
```sh
gfapy-convert path.gfa
```
```
Link L	A	+	B	+	4M has no identifier
Path conversion to GFA2 failed
```
Expected output
```gfa
S	A	10	AAAAAAACGT
S	B	10	ACGTCCACGT
E	*	A+	B+	6	10$	0	4	4M
O	P1	A+ B+
```
Alternative output
```gfa
S	A	10	AAAAAAACGT
S	B	10	ACGTCCACGT
E	1	A+	B+	6	10$	0	4	4M
O	P1	A+ 1+ B+
```

**Comment by ggonnella** [comment]
Good idea. I like the alternative output, i.e. assign unused IDs to the edges. The problem of leaving the edge used in the O without an ID arises if there is more than one edge, with different cigars, connecting the segments, in which case the ID is required. For the case above, it is indeed not.

**Comment by ggonnella** [comment]
The new strategy is to add an ID (at the moment using the custom id tag) to all GFA1 L lines which have none. This allows to process the lines with no particular order (otherwise one has to change the logic of the conversion, in order to process P lines before L and check which L do really need an id. I think this is a good compromise.

The side effect of this change is that the L id-tag IDs go in the same namespace as the S/P (i.e. they must be different from each other, and from S and P IDs). This is not in the specification, so I will add a text regarding the ID namespace in gfapy to the documentation.
