### ISSUE TITLE
Compact the assembly graph [feature request]

### ISSUE THREAD

**Issue by sjackman** [ggonnella/gfapy#9]
I'd like to compact the assembly graph (merge all possible segments). Bandage has this feature from the GUI, but doesn't expose it to the command line. See https://github.com/rrwick/Bandage/wiki/Editing-graphs#merge-all-possible-nodes

I'm currently interested in this feature for assembly graphs where all the overlap edges are blunt `0M`, which makes merging the sequences trivial. This operation is also easy if the overlaps are perfect `1234M`, but gets tricky if indels are involved. I'm not currently interested in handling indels.

**Comment by ggonnella** [comment]
I am sorry I did not answer properly to the feature request. Since I am cleaning up unfinished tasks I do it now, with only 2 and a half years delay. Sorry :( Actually a method already existed (I think also back then): merge_linear_paths(). I checked now with some tests that it also works with blunt ends (it does, correctly). Therefore I close the issue. Thank you, Shaun, and sorry again for the missing communication.
